databases:
 - name: scaffold_article
   databaseName: scaffold_article
   user: scaffold_article

services:
 - type: web
   name: scaffold_article
   env: ruby
   buildCommand: "./bin/render-build.sh"
   startCommand: "bundle exec puma -C config/puma.rb"
   envVars:
     - key: DATABASE_URL
       fromDatabase:
         name: scaffold_article
         property: connectionString
     - key: RAILS_MASTER_KEY
       sync: false